config/routes.rb
Musynapp::Application.routes.draw do

  resources :requests, only: :index do
    member { post :accept }
    member { post :reject }
    collection { post :manage_selection }
  end

  resources :conversations do 
    member { post :send_message }
  end

  resources :shows do
    member { post 'request_address' }
  end
  
  resources :venues, only: [:edit, :edit_media, :add_show, :index]

  resources :registrations, only: [:new, :create] do
    collection { post   'login' }
    collection { delete 'logout' }
    member     { post   'skip' }
  end

  resources :uploads, only: [:create, :destroy] do 
    member { get 'download' }
    member { post 'make_primary' }
  end


  resources :fans, only: [:edit, :update, :show, :destroy] do
    collection { get 'find' }
  end

  resources :venues, only: [:edit, :update, :show, :destroy] do
    member { get 'edit_media' }
    member { get 'add_show' }
    collection { get 'find' }
  end

  resources :bands, only: [:edit, :update, :show, :destroy] do
    member { get 'edit_media' }
    collection { get 'find' }
    resources :images, only: :destroy, shallow: true
  end

  resources :searches, only: [:index] do
    collection { get 'search' }
  end

  root 'welcome#index'

end

app/views/shared/_header.html.haml
.navbar.navbar-fluid-top
  .navbar-inner
    .container-fluid
      .pull-left
        = link_to 'Musynapp', root_path, class: 'brand'
      .pull-right
        %div{ style: 'margin-top:15px;'}
        .row-fluid
          .span6
            = form_tag search_searches_path, method: :get do 
              = text_field_tag 'query', '', class: 'search-query input-medium', placeholder: 'Search'
              = hidden_field_tag :search_type, 'simple'
              = submit_tag '', class: 'invisible'
          .span6
            - if current_user
              %ul.nav.nav-list{style: 'display:inline;'}
                %li.nav-header
                  %i.pull-left
                    - if !current_user.is?('Admin')
                      = link_to current_user.username, polymorphic_url(current_user.registrateable), id: 'my_profile'
                    - else
                      Admin
              = link_to "Log out", logout_registrations_path, method: :delete, class: 'btn'
            - else
              = form_tag login_registrations_path do
                = text_field_tag 'username', '', placeholder: 'Username', class: 'search-query'
                %br
                = text_field_tag 'password', '', placeholder: 'Password', type: 'password', class: 'search-query'
                = submit_tag 'Log in', class: 'btn'
                %br
                = link_to 'Sign Up', new_registration_path
                %br
                = link_to 'Forgot Password?', '#'
                = submit_tag '', class: 'invisible'

app/views/shared/_media_side_content.html.haml
- if content_type == :image
  - media.each do |img|
    %a.thumbnail{ href: img.upload.url }
      = image_tag img.upload.url(:thumb)
- if content_type == :song and media.present?
  %table.table
    %thead
      %tr
        %td 
          %b Playable sample songs
    - media.each do |song|
      %tr
        %td
          %div
            = song
          %audio{ controls: true }
            %source{ src: song.upload.url, type: song.upload.content_type }
- if content_type == :video
  - media.each do |video|
    %video{ controls: 'true', width: '320', height: '340' }
      %source{ src: "#{video.upload.url}", type: "#{video.upload.content_type}" }
- if content_type == :menu and media
  %a{ href: "#{media.upload.url}" }
    %img{ src: "#{media.thumb}" }

app/views/shared/_media_uploader.html.haml
= form_tag(uploads_path, id: "fileupload-#{media_type}") do
  .progress{ style: 'display: none;'}
    .bar
  = hidden_field_tag :user_type, object.class.to_s.downcase
  = hidden_field_tag :user_id, object.id
  .row.fileupload-buttonbar
    .span7
      %span.btn.btn-success.fileinput-button
        %i.icon-plus.icon-white
        %span 
          Add files...
          = file_field_tag "#{media_type}[upload]", multiple: true
    .span5
      .progress.progress-success.progress-striped.active.fade
        .bar{:style => "width:0%;"}
  %table.table{ id: "fileupload-#{media_type}-tmpl" }
    - [object.send(media_type)].flatten.compact.each do |media_item|
      = render 'shared/uploader_item', item: media_item.to_jq_upload

app/views/shared/_new_message_modal.html.haml
#myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      = form_tag Conversation.new do |f|
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
          %h3#myModalLabel
            = "Message to"
            %small
              = recipient.name
        .modal-body
          %label Subject
          %input#messageSubject{type: 'text', name: 'message[subject]'}
          %label Message
          %textarea#messageBody{rows: 8, name: 'message[body]'}
        .modal-footer
          = hidden_field_tag :recipient_id, recipient.id
          = hidden_field_tag :recipient_type, recipient.class.to_s
          %input.btn.btn-primary{type: 'Submit', value: 'Send'}
          %button.btn{"aria-hidden" => "true", "data-dismiss" => "modal"} Close

app/views/shared/_upcoming_shows.html.haml
%table.table
  %thead
    %tr
      %th Upcoming shows
  - shows.each do |show|
    %tr
      %td
        = link_to "#{show.address} @ #{show.humanized_time}", show