config/routes.rb
Musynapp::Application.routes.draw do

  resources :requests, only: :index do
    member { post :accept }
    member { post :reject }
    collection { post :manage_selection }
  end

  resources :conversations do 
    member { post :send_message }
  end

  resources :shows do
    member { post 'request_address' }
  end
  
  resources :venues, only: [:edit, :edit_media, :add_show, :index]

  resources :registrations, only: [:new, :create] do
    collection { post   'login' }
    collection { delete 'logout' }
    member     { post   'skip' }
  end

  resources :uploads, only: [:create, :destroy] do 
    member { get 'download' }
    member { post 'make_primary' }
  end


  resources :fans, only: [:edit, :update, :show, :destroy] do
    collection { get 'find' }
  end

  resources :venues, only: [:edit, :update, :show, :destroy] do
    member { get 'edit_media' }
    member { get 'add_show' }
    collection { get 'find' }
  end

  resources :bands, only: [:edit, :update, :show, :destroy] do
    member { get 'edit_media' }
    collection { get 'find' }
    resources :images, only: :destroy, shallow: true
  end

  resources :searches, only: [:index] do
    collection { get 'search' }
  end

  root 'welcome#index'

end

app/models/venue.rb
class Venue < ActiveRecord::Base

  acts_as_messageable
  scoped_search :on => [:name, :address]
  
  include Autocomplete

  has_one :registration, as: :registrateable, dependent: :destroy
  has_one :menu
  has_many :videos, dependent: :destroy
  has_many :images, as: :imageable, dependent: :destroy
  has_many :shows, dependent: :destroy
  has_many :requests_received, as: :requested, class_name: 'Request', dependent: :destroy
  has_many :requests_sent, as: :requester, class_name: 'Request', dependent: :destroy
  has_and_belongs_to_many :fans

  before_destroy { fans.clear }

  serialize :links

  def virtual?
    registration.nil?
  end
  
  # Required for Mailboxer gem to work
  def mailboxer_email(obj)
    nil
  end

  def to_s
    name
  end

end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  load_and_authorize_resource edit: [:edit_media, :add_show]

  def show
    continue_registration_or_redirect_to @venue
  end

  def edit
  end

  def edit_media
  end

  def add_show
  end

  def update
    update_registrateable_process @venue, venue_params
  end

  def index
  end

  def destroy
    @venue.destroy
    flash[:info] = "This account has been canceled"
    redirect_to root_path
  end

  def find
    render json: Venue.to_autocomplete(params[:query])
  end


  private

  def venue_params
    @params ||= params.require(:venue).permit(:name, :address, :links, :description, :menu,
                                  { videos_attributes: [:upload], images_attributes: [:upload] })
  end

end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/edit.html.haml
= simple_form_for @venue do |f|
  = f.input :name
  = f.input :address
  = f.input :description
  = f.button :submit, value: 'Done', class: 'btn btn-primary'

app/views/venues/edit_media.html.haml
%h2 Upload an image
= render partial: 'shared/media_uploader', locals: { media_type: 'images', object: @venue }
%h2 Upload a video
= render partial: 'shared/media_uploader', locals: { media_type: 'videos', object: @venue }
%h2 Uplaod a menu
= render partial: 'shared/media_uploader', locals: { media_type: 'menu', object: @venue }
= link_to 'Done', venue_path(@venue, 'venue[done]'=> true), class: 'btn btn-primary', method: 'put'

app/views/venues/edit_schedule.html.haml
%h1 Venues#edit_schedule
%p Find me in app/views/venues/edit_schedule.html.haml

app/views/venues/show.html.haml
%h1
  = @venue.name
- if can?(:edit, @venue)
  = link_to 'Edit media', edit_media_venue_path(@venue), class: 'btn'
  = link_to 'Edit info',  edit_venue_path(@venue), class: 'btn'
- if can?(:view_private_communication, @venue.registration)
  = link_to 'Requests box', requests_path, class: 'btn'
  = link_to 'Message box', conversations_path, class: 'btn'
  = link_to 'Propose a show', new_show_path, class: 'btn'
- if can?(:send_message, @venue.registration)
  %a.btn{"data-toggle" => "modal", href: "#myModal", role: "button"} Send a message
  = render partial: 'shared/new_message_modal', locals: { recipient: @venue }
- if can?(:destroy, @venue)
  = link_to 'Destroy venue account', @venue, method: :delete, class: 'btn btn-danger', 'data-confirm'=>'Are you sure?'
.row-fluid
  .span4
    = render partial: 'shared/media_side_content', locals: { content_type: :image, media: @venue.images }
    = render partial: 'shared/media_side_content', locals: { content_type: :video, media: @venue.videos }
    = render partial: 'shared/media_side_content', locals: { content_type: :menu, media: @venue.menu }
  .span4
    %dl
      %dt Description:
      %dd
        = @venue.description
      %dt Address:
      %dd
        = @venue.address
  .span3
    = render partial: 'shared/upcoming_shows', locals: { shows: Show.upcoming_for(@venue) }