config/routes.rb
Musynapp::Application.routes.draw do

  resources :requests, only: :index do
    member { post :accept }
    member { post :reject }
    collection { post :manage_selection }
  end

  resources :conversations do 
    member { post :send_message }
  end

  resources :shows do
    member { post 'request_address' }
  end
  
  resources :venues, only: [:edit, :edit_media, :add_show, :index]

  resources :registrations, only: [:new, :create] do
    collection { post   'login' }
    collection { delete 'logout' }
    member     { post   'skip' }
  end

  resources :uploads, only: [:create, :destroy] do 
    member { get 'download' }
    member { post 'make_primary' }
  end


  resources :fans, only: [:edit, :update, :show, :destroy] do
    collection { get 'find' }
  end

  resources :venues, only: [:edit, :update, :show, :destroy] do
    member { get 'edit_media' }
    member { get 'add_show' }
    collection { get 'find' }
  end

  resources :bands, only: [:edit, :update, :show, :destroy] do
    member { get 'edit_media' }
    collection { get 'find' }
    resources :images, only: :destroy, shallow: true
  end

  resources :searches, only: [:index] do
    collection { get 'search' }
  end

  root 'welcome#index'

end

app/models/fan.rb
class Fan < ActiveRecord::Base
  has_attached_file :avatar
  has_one :registration, as: :registrateable, dependent: :destroy
  has_many :friendships, class_name: 'FanFriendship', dependent: :destroy
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "FanFriendship", :foreign_key => "friend_id", dependent: :destroy
  has_many :inverse_friends, :through => :inverse_friendships, :source => :fan
  has_many :requests_sent, as: :requester, class_name: 'Request', dependent: :destroy
  has_and_belongs_to_many :favorite_venues, class_name: 'Venue'
  has_and_belongs_to_many :favorite_bands, class_name: 'Band'
  has_and_belongs_to_many :shows

  before_destroy { favorite_bands.clear; favorite_venues.clear }


  include Autocomplete

  def friends_ids
    friends.to_json(only: [:id, :name])
  end

  def friends_ids= ids
    friendships.clear
    ids[0].split(',').select(&:present?).map do |friend_id|
      friendships.build friend_id: friend_id
    end
  end

  def favorite_venues_ids
    favorite_venues.to_json(only: [:id, :name])
  end

  def favorite_venues_ids= ids
    favorite_venues.clear
    ids[0].split(',').select(&:present?).map do |venue_id|
      favorite_venues << Venue.find(venue_id)
    end
  end

  def favorite_bands_ids
    favorite_bands.to_json(only: [:id, :name])
  end

  def favorite_bands_ids= ids
    favorite_bands.clear
    ids[0].split(',').select(&:present?).map do |band_id|
      favorite_bands << Band.find(band_id)
    end
  end

  # TODO:
  # def favorites= type, ids

end

app/controllers/fans_controller.rb
class FansController < ApplicationController

  load_resource
  authorize_resource except: :show

  def show
    continue_registration_or_redirect_to @fan
  end

  def edit
  end

  def update
    if @fan.update_attributes(fan_params)
      proceed_registration || redirect_to(@fan)
    else
      flash.now[:error] = @fan.errors.messages.map{ |key,val| "#{key} #{val}\n" } 
      render( current_user.current_step || params[:form_id] )
    end
  end

  def destroy
    @fan.destroy
    flash[:info] = "This account has been canceled"
    redirect_to root_path
  end

  def find
    render json: Fan.to_autocomplete(params[:query])
  end


  private

  def fan_params
     params.require(:fan).permit(:name, :avatar, favorite_bands_ids: [],
                                  favorite_venues_ids: [],
                                  friends_ids: [])
  end

end

app/helpers/fan_helper.rb
module FanHelper
end

app/views/fans/_info_panel.html.haml
.panel.panel-default
  .list-expander.panel-heading 
    %h4
      = title
  .panel-body
    .list-group
      - collection.each do |item|
        = link_to item.name, item, class: 'list-group-item'

app/views/fans/edit.html.haml
.row-fluid
  .span8
    = simple_form_for @fan do |f|
      = f.input :avatar, as: :file
      = f.input :name
      = f.label :friends
      = f.input_field :friends_ids, data: { delimiter: ',', placeholder: "Look up for friends", url: find_fans_path }, multiple: true, inline_label: 'Friends', class: "select2 input-block-level"
      %br
      = f.label :favorite_bands
      = f.input_field :favorite_bands_ids, data: { delimiter: ',', placeholder: "Look up for your favorite bands", url: find_bands_path }, multiple: true, class: "select2 input-block-level"
      %br
      = f.label :favorite_venues
      = f.input_field :favorite_venues_ids, data: { delimiter: ',', placeholder: "Look up for your favorite venues", url: find_venues_path }, multiple: true, class: "select2 input-block-level"
      %br
      = f.button :submit, value: 'Done', class: 'btn btn-primary'

app/views/fans/show.html.haml
%h1
  = @fan.name
- if can?(:edit, @fan)
  = link_to 'Edit', edit_fan_path(@fan), class: 'btn'
- if can?(:destroy, @fan)
  = link_to 'Destroy fan account', @fan, method: :delete, class: 'btn btn-danger', 'data-confirm'=>'Are you sure?'
.row-fluid
  .span4
    %a.thumbnail
      = image_tag @fan.avatar.url
  .span7
    - { 'Friends' => @fan.friends, 'Favorite bands' => @fan.favorite_bands, 'Favorite venues' => @fan.favorite_venues }.each do |title, collection|
      = render partial: 'info_panel', locals: { title: title, collection: collection }