config/routes.rb
Musynapp::Application.routes.draw do

  resources :requests, only: :index do
    member { post :accept }
    member { post :reject }
    collection { post :manage_selection }
  end

  resources :conversations do 
    member { post :send_message }
  end

  resources :shows do
    member { post 'request_address' }
  end
  
  resources :venues, only: [:edit, :edit_media, :add_show, :index]

  resources :registrations, only: [:new, :create] do
    collection { post   'login' }
    collection { delete 'logout' }
    member     { post   'skip' }
  end

  resources :uploads, only: [:create, :destroy] do 
    member { get 'download' }
    member { post 'make_primary' }
  end


  resources :fans, only: [:edit, :update, :show, :destroy] do
    collection { get 'find' }
  end

  resources :venues, only: [:edit, :update, :show, :destroy] do
    member { get 'edit_media' }
    member { get 'add_show' }
    collection { get 'find' }
  end

  resources :bands, only: [:edit, :update, :show, :destroy] do
    member { get 'edit_media' }
    collection { get 'find' }
    resources :images, only: :destroy, shallow: true
  end

  resources :searches, only: [:index] do
    collection { get 'search' }
  end

  root 'welcome#index'

end

app/models/band.rb
class Band < ActiveRecord::Base

  acts_as_messageable
  scoped_search on: :name
  scoped_search in: :genre, on: :title

  include Autocomplete
  
  has_one :registration, as: :registrateable, dependent: :destroy
  has_many :songs, dependent: :destroy
  has_many :images, as: :imageable, dependent: :destroy
  has_many :shows, dependent: :destroy
  has_and_belongs_to_many :fans
  belongs_to :genre
  has_many :requests_received, as: :requested, class_name: 'Request', dependent: :destroy
  has_many :requests_sent, as: :requester, class_name: 'Request', dependent: :destroy

  before_destroy { fans.clear }

  serialize :links

  before_create :prepare_links, if: -> { self.links.present? }

  def virtual?
    registration.nil?
  end

  def to_s
    name
  end

  # Required for Mailboxer gem to work
  def mailboxer_email(obj)
    nil
  end


  private

  def prepare_links
    self.links = self.links.split(',').map(&:strip)
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  
  load_resource edit: [:edit_media, :request_address]
  authorize_resource except: :show

  def show
    continue_registration_or_redirect_to @band
  end

  def edit
  end

  def edit_media
  end

  def update
    update_registrateable_process @band, band_params
  end

  def destroy
    @band.destroy
    flash[:info] = "This account has been canceled"
    redirect_to root_path
  end

  def find
    render json: Band.to_autocomplete(params[:query])
  end

  def request_address
    @band.send_address_request_for current_user.registrateable
    flash[:info] = 'Your request is sent'
    redirect_to :back
  end

  
  private

  def band_params
    params.require(:band).permit(:name, :genre_id, :description, :links, :id,
                                 { songs_attributes: [:upload], images_attributes: [:upload] } )
  end

end

app/views/bands/edit.html.haml
= simple_form_for @band do |f|
  = f.input :name
  = f.association :genre
  = f.input :description
  = f.input :links, label: 'Input comma-sparated links', input_html: { value: f.object.links.try(:join, ', ') }
  = f.button :submit, value: 'Done', class: 'btn btn-primary'

app/views/bands/edit_media.html.haml
%h2 Upload an image
= render partial: 'shared/media_uploader', locals: { media_type: 'images', object: @band }
%h2 Upload a song
= render partial: 'shared/media_uploader', locals: { media_type: 'songs', object: @band }
= link_to 'Done', band_path(@band, 'band[id]'=> @band.id), class: 'btn btn-primary', method: 'put'

app/views/bands/show.html.haml
%h1 
  = @band.name
- if can?(:edit, @band)
  = link_to 'Edit media', edit_media_band_path(@band), class: 'btn'
  = link_to 'Edit info',  edit_band_path(@band), class: 'btn'
- if can?(:view_private_communication, @band.registration)
  = link_to 'Requests box', requests_path, class: 'btn'
  = link_to 'Message box', conversations_path, class: 'btn'
  = link_to 'Propose a show', new_show_path, class: 'btn'
- if can?(:send_message, @band.registration)
  %a.btn#sendMessage{"data-toggle" => "modal", href: "#myModal", role: "button"} Send a message
- if can?(:destroy, @band)
  = link_to 'Destroy band account', @band, method: :delete, class: 'btn btn-danger', 'data-confirm'=>'Are you sure?'
= render partial: 'shared/new_message_modal', locals: { recipient: @band }
.row-fluid
  .span4
    = render partial: 'shared/media_side_content', locals: { content_type: :image, media: @band.images }
    = render partial: 'shared/media_side_content', locals: { content_type: :song, media: @band.songs }
  .span4
    %dl
      %dt Description:
      %dd
        = @band.description
      %dt Links:
      %dd
        %ul
          - if @band.links.present?
            - @band.links.split(',').each do |link|
              %li
                = link_to_if valid?(link), link, link
  .span3
    = render partial: 'shared/upcoming_shows', locals: { shows: Show.upcoming_for(@band) }